### ISSUE TITLE
add section "Our news" in home page

### ISSUE THREAD

**Issue by josebaptista12** [josebaptista12/WeRise#1]
Create a section in home page (e.g a table) where we will be putting our news.

**Comment by DimitraPetrakou** [comment]
Hello! Can you assign this to me ?

**Comment by josebaptista12** [comment]
sure!

**Comment by DimitraPetrakou** [comment]
I created a table with 3 columns for the 'our news' section. I used the colors that you are already using. I hope it is what you wanted :)
