### ISSUE TITLE
fix contact page

### ISSUE THREAD

**Issue by josebaptista12** [josebaptista12/WeRise#4]
In the contact page we need a form for people to apply themselves, if they want to join our team. The form should include "name", "email" and "some things about yourself". Also add in the page the photo "join.jpg".

**Comment by DimitraPetrakou** [comment]
can you assignt this to me?

**Comment by DimitraPetrakou** [comment]
How would you like the layout of the page? Where should I put the photo ?

**Comment by josebaptista12** [comment]
Hello! On the left side of the page you could put the form and on the right side of the page you could put the photo. Also put a title to the page (e.g. "Join our team").

**Comment by josebaptista12** [comment]
Also the footer should be at the bottom of the page
